#### Application Metadata ########
spring.application.name=easysplit
server.servlet.context-path=/easysplit
server.port=8082

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/easysplitdb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

#######  Logging #########
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=DEBUG
logging.file=/var/log/easysplit.log
logging.level.org.springframework=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
